### ISSUE TITLE
Works standalone, crashes in REAPER

### ISSUE THREAD

**Issue by probonopd** [probonopd/MultiDexed#15]
This plugin is supposed to recreate a "Unison" effect for the Dexed synthesizer:
* Load multiple instances of Dexed, each slightly detuned and stereo panned
* Mirror all parameter changes of the master Dexed instance (instance 0) cto the other instances (instances 1-4)
* Let the user change the amount of detune and stereo panning across Dexed instances 1-4

As of [63b1258](https://github.com/probonopd/MultiDexed/commit/63b1258ef86800eb12e414ee79154ed696604e2c), this works standalone, but crashes in REAPER.

It has taken me weeks now to wrap my head around JUCE but I must be missing something quite essential, since not even the examples that come with JUCE seem to be working for me.

Be sure to switch on the sound by using the loudspeaker icon in the borttom right of the video:

https://github.com/probonopd/MultiDexed/assets/2480569/b1fd662a-7b84-4be5-93bb-41dee05ee223

The only plugin that seemingly can load plugins and do the kinds of things I am looking to do here appears to be [pluginguru Unify](https://www.pluginguru.com/products/unify-standard/) by @getdunne which is an awesome plugin that can do 1,001 things more than what I am trying to do here. And unfortunately I can't use it because it doesn't work on the OSes I am interested in (Linux, FreeBSD).

Cross-reference:
* https://forum.juce.com/t/plugin-and-standalone-linux-and-windows-behave-crash-differently/56308

**Comment by probonopd** [comment]
...and the Windows VST3 running in REAPER doesn't have the sliders working at all. They are just blocked.
(I can still edit the parameters by clicking on the "UI" button in REAPER through.)

Why am I getting different issues on different OSes? Isn't JUCE supposed to work the same on all platforms?

**Comment by getdunne** [comment]
Have a look at Kushview Element: https://github.com/kushview/element. GPL-3, runs on Linux/Mac/Win, Linux build available: https://github.com/kushview/element/releases/tag/0.46.6

**Comment by probonopd** [comment]
Thanks @getdunne. I had a look at it but it also seems to do way more than what I need.

Turns out that the issues only appear when trying to load a JUCE 6 based plugin (here: Dexed 0.9.6) into this host plugin; the issues go away when using the NIGHTLY build of Dexed which is based on JUCE 7.

reuk over at the JUCE forum suggested:

> Dexed 0.9.6 was using JUCE 6, which didn’t have very good support for the event loop on Linux. I expect that you might see crashes due to threading issues, or due to undelivered messages in this case

So I was trying to solve the issues in the wrong place (my code) all the time when in fact the issues were somewhere else entirely (Linux threading/event loop/messages in JUCE 6).

In any case, thanks a lot for your help!
