### ISSUE TITLE
Build for Windows

### ISSUE THREAD

**Issue by probonopd** [probonopd/MultiDexed#6]
Since many VSTs are only available for Windows (and the Mac), even on open source operating systems it may be preferable to run Windows versions of VSTs. So we should build this for Windows.

Microsoft conveniently provides free virtual machines of Windows with a compiler preinstalled:

https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ (the one for VirtualBox is 21 GB large, though)

**Comment by Kirtai** [comment]
No LV2? I believe the newest JUCE supports it.

**Comment by probonopd** [comment]
What I meant is: Many of the plugins we like to run in our DAWs are only available for Windows (and the Mac), so pragmatically on Linux and BSD it may be preferable to run the DAW under WINE. Which is why we should also have a MultiDexed for WINE.

**Comment by probonopd** [comment]
Since I normally don't run Windows, let me write down the steps. Using this approach requires a powerful recent computer with "lots" (16 GB) of RAM and even more fast SSD space.

* Download https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ (22 GB), it comes with Visual Studio Community 2022 which includes a C++ compiler
* Unzip (another 22 GB)
* Import into VirtualBox (another 22 GB)
* Set RAM to 12 GB and increase CPU cores
* First thing before booting, make a snapshot in VirtualBox
* Add an optical drive to the VM so that you can install Guest Extensions
* Boot Windows (first boot takes ~20 minutes)
* Install Guest Extensions (6.1.36 is what comes with the VirtualBox on FreeBSD 13.1-RELEASE with 2023Q1 packages)
* Reboot
* **Why can't I resize the screen?** 
* Shut down
* Make another snapshot
* Download and install JUCE to `C:\JUCE`
* Open Visual Studio and clone this repository
* Open Projucer
* Create a VisualStudio build configuration
* Double click the respective `*.vcxproj` and open with Visual Studio Community 2022
* Press F7 to build
* It compiles straight away without a hitch
* Running the standalone version seems to crash, as a window is never shown
* Running it with the Visual Studio Community 2022 debugger, we see that it seems to crash on `File::parseAbsolutePath`. I have never seen such a seamless and useful debugging information anywhere before... Sure enough, when changing the path to Dexed in `PluginProcessor.cpp` to `C:\Program Files\Common Files\VST3\Dexed.vst3`, then this crash goes away...
* Now the debugger says that "`dexedPluginNode1` was nullptr"

We should possibly find and instantiate Dexed in a platform independent way, something along these lines:

```
PluginAudioProcessor::PluginAudioProcessor()
{
    juce::VST3PluginFormat vst3Format;
    juce::PluginDescription dexedDescription;

    description.name = "Dexed";
    description.manufacturerName = "Digital Suburban";
    description.pluginFormatName = "VST3";

    juce::AudioPluginInstance* dexedPluginNode1 = vst3Format.createInstanceFromDescription(dexedDescription, getSampleRate(), getBlockSize()).release();
 ```

**Comment by probonopd** [comment]
It now builds for Windows, macOS, and Linux using GitHub Actions. That it crashes is probably not due to the compilation, but due to stupid bugs in the code. Will be tracked in separate issues.

**Comment by probonopd** [comment]
As for the resultion, I had to run

```
sudo vboxmanage list vms # Get the name of the VM
sudo VBoxManage setextradata global GUI/MaxGuestResolution any
sudo VBoxManage setextradata  "WinDev2302Eval" "CustomVideoMode1" "1920x1080x32"
sudo VBoxManage controlvm "WinDev2302Eval" setvideomodehint 1920 1080 32
```
