### ISSUE TITLE
Do not get any sound, getting JUCE Assertion failures

### ISSUE THREAD

**Issue by probonopd** [probonopd/MultiDexed#9]
I a trying to host two instances of the [Dexed](https://github.com/asb2m10/dexed) plugin, and get sound from them into my MultiDexed plugin. (Eventually, I want to slightly detune and stereo pan them to get a "fat" sound.)

But I can't seem to get any sound from the hosted instance(s).

On Ubuntu, running the standalone version gives somewhat vague hints about what might be going wrong:

```
~/MultiDexed/Builds/LinuxMakefile$ ./build/MultiDexed
JUCE v7.0.5
Plugin Path: /usr/lib/vst3/Dexed.vst3
Loaded Plugin: Dexed
Loaded Plugin: Dexed
JUCE Assertion failure in juce_AudioProcessor.cpp:1074
JUCE Assertion failure in juce_AudioProcessor.cpp:111
kResultFalse
JUCE Assertion failure in juce_AudioProcessor.cpp:111
kResultFalse
JUCE Assertion failure in juce_Component.cpp:1143
```

I spent a lot of time on it but cannot figure out how to fix this. It seems that `prepareToPlay` causes the `kResultFalse`. Likely something about seting up the channels layout?

@hogliux seems to have been the main author of the key files in
https://github.com/getdunne/juce-plugin-wrapper, so possibly he or @getdunne might be able to help me here? I'd really deeply appreciate it.

**Comment by probonopd** [comment]
On Ubuntu, running the standalone version gives somewhat vague hints about what might be going wrong:

```
~/MultiDexed/Builds/LinuxMakefile$ ./build/MultiDexed
JUCE v7.0.5
Plugin Path: /usr/lib/vst3/Dexed.vst3
Loaded Plugin: Dexed
Loaded Plugin: Dexed
JUCE Assertion failure in juce_AudioProcessor.cpp:1074
JUCE Assertion failure in juce_AudioProcessor.cpp:111
kResultFalse
JUCE Assertion failure in juce_AudioProcessor.cpp:111
kResultFalse
JUCE Assertion failure in juce_Component.cpp:1143
```

I spent a lot of time on it but cannot figure out how to fix this. It seems that `prepareToPlay` causes the `kResultFalse`. Likely something about seting up the channels layout?

@hogliux seems to have been the main author of the key files in
https://github.com/getdunne/juce-plugin-wrapper, so possibly he or @getdunne might be able to help me here? I'd really deeply appreciate it.

**Comment by getdunne** [comment]
I'll have a look, but I'm not set up to build anything on Linux at the moment.

**Comment by probonopd** [comment]
Thank you very much @getdunne. It should also work on macOS and Windows (at least it [compiles](https://github.com/probonopd/MultiDexed/actions/runs/4778951896)).
I think the error is the same on all platforms. I just used Linux for my development setup, but I think you'll be able to reproduce the same on macOS or Windows as well.

**Comment by getdunne** [comment]
I found several small issues. I didn't want to fork your repo just so I could send you a pull request, so I've packaged up my changes (with a "readme" file with details) into a zip you can download here: https://www.dropbox.com/s/f5ndv5rrvvg8g9y/MultiDexedChanges.zip?dl=0

**Comment by probonopd** [comment]
Thank you very, very much @getdunne for taking the time to help me. This is tremendously helpful.

I hope it is ok for me to merge your changes (with proper attribution of course) into this repo.

Maybe this example for hosting a VST will be useful for others, too.

Mirroring the file here for future reference in case Dropbox link breaks:
[MultiDexedChanges.zip](https://github.com/probonopd/MultiDexed/files/11313442/MultiDexedChanges.zip)

**Comment by getdunne** [comment]
Yes, by all means merge the changes. Don't worry about attribution; these are just minor bug fixes. Good luck with this project.
